title: English Now!
email: info@english-now.com
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://washingtoncie.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [ruby, Gemfile, Gemfile.lock, vendor]
include:
    - _pages
